global:
  scrape_interval: 15s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus-server'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: 'node-exporter-container'

